---
version: "3.7"

services:
  database:
    container_name: tasks-db
    image: postgres:14.2
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xablau
      POSTGRES_DB: tasks
      LC_ALL: C
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data
